### ISSUE TITLE
Missing PyJWT in setup.py?

### ISSUE THREAD

**Issue by mblayman** [audiolion/apistar-jwt#1]
Hi, @audiolion. I noticed your project on the Discuss site so I thought I'd check it out. I see that the code calls `import jwt`, but I don't see `PyJWT` as a dependency in `setup.py`. Am I missing something?

Thanks for you efforts so far. I look forward to a time where API Star has a robust 3rd party ecosystem.

**Comment by audiolion** [comment]
Oh great catch! Had it in my Pipfile and forgot to put it in there

https://github.com/audiolion/apistar-jwt/blob/5bcfd26bc35fcf9d8f380d5e6df1f843fb7c1fed/Pipfile#L6-L9

**Comment by audiolion** [comment]
Already made a new release on PyPI 0.1.2

**Comment by audiolion** [comment]
Yeah I actually haven't gotten the tests up yet, I have used tox in the past but only because I was testing across a bunch of python versions, but since API Star is 3.5+ only I didn't feel the need, also I wasn't sure how to get tox to work with `pipenv`, if you want to submit a PR to get tox working with it though it would be appreciated!
